version: '3'

services:
  django:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: django
      POSTGRES_USER: django
      POSTGRES_PASSWORD: 123password456
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    depends_on:
      - django
  celery:
    build: .
    image: celery:latest
    command: celery -A main worker --loglevel=INFO --logfile=celery.log
    volumes:
          - .:/app
    depends_on:
      - django
      - redis
